version: "3.9"

services:
  db:
    build:
      dockerfile: ./Dockerfile
    restart: always
    container_name: dvd_rental_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvd_rental
    ports:
      - 5432:5432
    volumes:
      - dvd_rental_data:/var/lib/postgresql/data

volumes:
  dvd_rental_data:

