name: "Docker Compose"

runs:
  using: "composite"
  steps:
    - name: Download Docker Compose
      shell: bash
      run: curl -SL https://github.com//docker/compose/releases/download/v2.33.1/docker-compose-darwin-x86_64 -o /usr/local/bin/docker-compose
    - name: Make binary executable
      shell: bash
      run: sudo chmod +x /usr/local/bin/docker-compose
    - name: Start services
      shell: bash
      run: docker compose up -d
